### ISSUE TITLE
Process configuration syntax $processName has been deprecated

### ISSUE THREAD

**Issue by BasBerbers** [tiagofilipe12/pATLASflow#15]
Hi,

I wanted to use pATLAS on an assembled plasmid ,however when I run pATLASflow it gives me multiple errors like this:

```
WARN  nextflow.processor.ProcessFactory - Process configuration syntax $processName has been deprecated -- Replace `process.$mashDistOutputJson = <value>` with a
process selector
```

I also added the nextflow log file below:

[nextflow.log](https://github.com/tiagofilipe12/pATLASflow/files/2726648/nextflow.log)

**Comment by tiagofilipe12** [comment]
Hi @BasBerbers ,

Glad you are giving pATLAS a try. Hope you enjoy it!

Actually the problem with the syntax isn't an error but rather a warning for the future of nextflow, and thus it shouldn't stop the pipeline.

But your log contains a different error:
```
Jan-04 10:39:07.230 [Actor Thread 9] ERROR nextflow.processor.TaskProcessor - Error executing process > 'mashDistOutputJson (dumping json file from: BC07_contig7.fas_mashdist.txt)'

Caused by:
  java.nio.file.ProviderMismatchException

java.nio.file.ProviderMismatchException: null
	at sun.nio.fs.UnixPath.toUnixPath(UnixPath.java:200)
	at sun.nio.fs.UnixFileSystemProvider.getFileAttributeView(UnixFileSystemProvider.java:115)
	at sun.nio.fs.LinuxFileSystemProvider.getFileAttributeView(LinuxFileSystemProvider.java:68)
	at sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:144)
	at sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.nio.file.Files.readAttributes(Files.java:1737)
	at nextflow.util.CacheHelper.hashFile(CacheHelper.java:203)
	at nextflow.util.CacheHelper.hasher(CacheHelper.java:158)
	at nextflow.util.CacheHelper.hasher(CacheHelper.java:150)
	at nextflow.util.CacheHelper.hasher(CacheHelper.java:90)
	at nextflow.util.CacheHelper.hasher(CacheHelper.java:86)
	at nextflow.util.CacheHelper$hasher.call(Unknown Source)
	at nextflow.processor.TaskProcessor.createTaskHashKey(TaskProcessor.groovy:1836)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168)
	at nextflow.processor.TaskProcessor.invokeTask(TaskProcessor.groovy:535)
	at nextflow.processor.InvokeTaskAdapter.call(InvokeTaskAdapter.groovy:58)
	at groovyx.gpars.dataflow.operator.DataflowOperatorActor.startTask(DataflowOperatorActor.java:120)
	at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor.access$001(ForkingDataflowOperatorActor.java:35)
	at groovyx.gpars.dataflow.operator.ForkingDataflowOperatorActor$1.run(ForkingDataflowOperatorActor.java:58)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Jan-04 10:39:07.237 [Actor Thread 9] DEBUG nextflow.Session - Session aborted -- Cause: java.nio.file.ProviderMismatchException
Jan-04 10:39:07.256 [Actor Thread 9] DEBUG nextflow.Session - The following nodes are still active:
[process] mashDistOutputJson
  status=ACTIVE
  port 0: (queue) closed; channel: -
  port 1: (cntrl) -     ; channel: $
```

I solved it and tested locally, but tell me something here if you run into troubles. Meanwhile, have a look at [FlowCraft](https://github.com/assemblerflow/flowcraft), which will be the long term support for these pipelines. pATLAS docs have documentation on how you should use it as well: https://patlas.gitbook.io/docs/usage/sidebar/import#flowcraft

However, this fix was currently added to the dev branch and thus you will have to git clone flowcraft instead of using the pip/conda regular installation to be able to use the fix. But in the meanwhile maybe you can use pATLASflow with the fix I pushed just minutes ago.

**Comment by BasBerbers** [comment]
Thank you for your fast response. And I wil give FlowCraft also a try.
